apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acm-open-hive
  namespace: hive
  annotations:
    apps.open-cluster-management.io/github-path: deployed
    apps.open-cluster-management.io/github-branch: main
  labels:
    subscription-pause: "false"
spec:
  channel: open-hive/gitops-hive
  placement:
   local: true
