# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: cluster-1

generatorOptions:
  disableNameSuffixHash: true

# list of Resource Config to be Applied
resources:
  - namespace.yaml
  - clusterdeployment.yaml
  - aws-cred-sealedsecret.yaml
  - ocp-private-key-sealedsecret.yaml
  - ocp-pull-sealedsecret.yaml
  - install-config-sealedsecret.yaml
